
services:
  kcserver:
    # build:
    #   context: ../../
    #   dockerfile: ./Dockerfile
    image: kcserver:1.0.1
    container_name: kcserver
    restart: always
    environment:
      TZ: Asia/Shanghai
    networks:
      kcserver:

    ports:
      - "10003:10003"
    volumes:
      - ./kcserver/config/:/app/config/
      - ./kcserver/log/:/app/log/

networks:
  kcserver:
    external: true
