version: '3'

services:
  kcserver:
    build:
      context: ..
      dockerfile: ./Dockerfile
    image: kcserver:latest
    container_name: kcserver
    restart: always
    environment:
      TZ: Asia/Shanghai
    networks:
      kcserver_net_1:
        ipv4_address: 172.24.0.2
      db_net_1:
      minio_net_1:
    external_links:
      - db_1
    ports:
      - "10003:10003"
    volumes:
      - ./config/:/app/config/
      - ./log/:/app/log/

networks:
  kcserver_net_1:
    name: kcserver_net_1
    driver: bridge
    ipam:
      config:
        - subnet: 172.24.0.0/16
          gateway: 172.24.0.1
  db_net_1:
    external: true
  minio_net_1:
    external: true
