
services:
  nginx:
    image: nginx:1.27.2-alpine3.20
    container_name: kchttps
    restart: unless-stopped
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
    environment:
      TZ: Asia/Shanghai
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d:/etc/nginx/conf.d
      - ./log:/var/log/nginx
      # - ./cert:/etc/nginx/cert
      - ./html:/usr/share/nginx/html
      - ./certs:/etc/ssl/certs
      - ./private:/etc/ssl/private
    networks:
      kcserver:
networks:
  kcserver:
    external: true