version: '3'

services:
  loginservice:
    build:
      context: ..
      dockerfile: ./loginservice/Dockerfile
    image: loginservice:latest
    container_name: loginservice
    networks:
      loginservice_net_1:
        ipv4_address: 172.21.0.2
      db_net_1:
    external_links:
      - db_1
    ports:
      - "10001:10001"
    volumes:
      - ./config/config.yaml:/app/config/config.yaml
      - ./log/all.log:/app/log/all.log

networks:
  loginservice_net_1:
    name: loginservice_net_1
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16
          gateway: 172.21.0.1
  db_net_1:
    external: true
