version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    networks:
      nginx_net_1:
#        ipv4_address: 172.22.0.2
    restart: always
    environment:
      TZ: Asia/Shanghai
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d:/etc/nginx/conf.d
      - ./log:/var/log/nginx
      - ./cert:/etc/nginx/cert

networks:
  nginx_net_1:
    driver: bridge
#    ipam:
#      config:
#        - subnet: 172.22.0.0/16
#          gateway: 172.22.0.1