db:
#  dsn: "root:_IpFCT^*pui~Mac7~0%SIicRq@Z6rtzE@tcp(localhost:33306)/kcserver?charset=utf8&parseTime=True&loc=Local"
  dsn: "root:_IpFCT^*pui~Mac7~0%SIicRq@Z6rtzE@tcp(192.168.0.18:33306)/kcserver?charset=utf8&parseTime=True&loc=Local"