
services:
  kcversion:
    # build:
    #   context: ../../
    #   dockerfile: ./Dockerfile
    image: kcversion:0.1.0
    container_name: kcversion
    restart: always
    environment:
      TZ: Asia/Shanghai
    networks:
      kcserver:

    # ports:
    #   - "10003:10003"
    volumes:
      - ./kcversion/config/:/app/config/
      - ./kcversion/log/:/app/log/

networks:
  kcserver:
    external: true
