version: '3'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    networks:
      kcserver:
    restart: always
    # ports:
      # - "27017:27017"
    environment:
      TZ: Asia/Shanghai
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: "_IpFCT^*pui~Mac7~0%SIicRq@Z6rtzE"
    volumes:
      - ./mongodb:/data/db

networks:
  kcserver:
    external: true