version: '3'

services:
  db_1:
    image: mysql:8.0.32
    container_name: mysql
    networks:
      kcserver:
#        ipv4_address: 172.21.0.2
    restart: always
    # ports:
      # - "33306:3306"
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
#      --bind-address=0.0.0.0
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=_IpFCT^*pui~Mac7~0%SIicRq@Z6rtzE
      - LANG=C.UTF-8
    volumes:
#      - /etc/localtime:/etc/localtime
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf/my.cnf:/etc/my.cnf
      - ./mysql/conf/conf.d:/etc/my.cnf.d
      - ./mysql/init:/docker-entrypoint-initdb.d

networks:
  kcserver:
#    name: db_net_1
#    driver: bridge
#    ipam:
#      config:
#        - subnet: 172.21.0.0/16
#          gateway: 172.21.0.1
    external: true