
services:
  redis:
    container_name: redis
    image: "redis:alpine"
    restart: always
    volumes:
      - "./redis:/data"
    networks:
      - kcserver
    command: redis-server --appendonly yes
    # ports:
      # - "6379:6379"

networks:
  kcserver:
    external: true
