apiVersion: v1
kind: Secret
metadata:
  name: kc-docker-registry-auth-secret
  namespace: kc
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "registry.protodesign.cn:36000": {
          "username": "kcserver",
          "password": "MEu2o91KHihnuLID6buRGrjRVo9YuM48"
        }
      }
    }
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kc
  namespace: kc
imagePullSecrets:
  - name: kc-docker-registry-auth-secret
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: 'true'
  name: kc-reader
rules:
  - apiGroups:
      - ''
    resources:
      - pods
      - services
    verbs:
      - get
      - watch
      - list


