CREATE TABLE `kcserver`.`invite_codes` (
  `id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `deleted_at` DATETIME(6),

  `code` VARCHAR(8) NOT NULL UNIQUE,
  `user_id` BIGINT NOT NULL
)
CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;