CREATE TABLE `kcserver`.`teams` (
  `id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `deleted_at` DATETIME(6),

  `name` VARCHAR(64) NOT NULL,
  `description` VARCHAR(128),
  `avatar` VARCHAR(256),
  `uid` VARCHAR(64) NOT NULL UNIQUE,
  `invited_perm_type` TINYINT NOT NULL DEFAULT 0,
  `invited_switch` BOOLEAN NOT NULL DEFAULT FALSE
)
CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;