CREATE TABLE `kcserver`.`projects` (
  `id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `deleted_at` DATETIME(6),

  `team_id` BIGINT NOT NULL,
  `name` VARCHAR(64) NOT NULL,
  `description` VARCHAR(128),
  `public_switch` BOOLEAN NOT NULL DEFAULT FALSE,
  `perm_type` TINYINT NOT NULL DEFAULT 1,
  `invited_switch` BOOLEAN NOT NULL DEFAULT FALSE,
  `need_approval` BOOLEAN NOT NULL DEFAULT TRUE
)
CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;