CREATE TABLE `kcserver`.`feedbacks` (
  `id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `deleted_at` DATETIME(6),

  `user_id` BIGINT NOT NULL,
  `type` TINYINT NOT NULL,
  `content` TEXT,
  `image_path_list` TEXT,
  `page_url` VARCHAR(255)
)
CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;