apiVersion: v1
kind: Service
metadata:
  name: kubeapps-nodeport
  namespace: kubeapps
spec:
  type: NodePort
  selector:
    app.kubernetes.io/component: frontend
    app.kubernetes.io/instance: kubeapps
    app.kubernetes.io/name: kubeapps
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
      nodePort: 30001
