apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: haproxy
    app.kubernetes.io/name: percona-xtradb-cluster
  name: pxc-mysql-nodeport
  namespace: pxc
spec:
  type: NodePort
  ports:
    - name: mysql-replicas
      port: 3306
      protocol: TCP
      targetPort: 3306
      nodePort: 30100
  selector:
    app.kubernetes.io/component: haproxy
    app.kubernetes.io/instance: pxc-mysql-pxc-db
    app.kubernetes.io/name: percona-xtradb-cluster
