kind: InitConfiguration
apiVersion: kubeadm.k8s.io/v1beta3
bootstrapTokens:
  - groups:
      - system:bootstrappers:kubeadm:default-node-token
    token: abcdef.0123456789abcdef
    ttl: 24h0m0s
    usages:
      - signing
      - authentication
localAPIEndpoint:
  advertiseAddress: $this_ip
  bindPort: 6443
nodeRegistration:
  criSocket: unix:///var/run/containerd/containerd.sock
  imagePullPolicy: IfNotPresent
  name: $node_name
  taints: []
---
kind: KubeletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1
maxPods: 1000
systemReserved:
  cpu: "200m"
  memory: "1Gi"
kubeReserved:
  cpu: "200m"
  memory: "0.5Gi"
  ephemeral-storage: "1Gi"
evictionHard:
  memory.available: "100Mi"
  nodefs.available: "10%"
  nodefs.inodesFree: "5%"
  imagefs.available: "15%"
---
kind: ClusterConfiguration
apiVersion: kubeadm.k8s.io/v1beta3
certificatesDir: /etc/kubernetes/pki
clusterName: kubernetes
controllerManager: {}
dns: {}
etcd:
  local:
    dataDir: /var/lib/etcd
imageRepository: registry.cn-hangzhou.aliyuncs.com/google_containers
kubernetesVersion: 1.28.0
networking:
  dnsDomain: cluster.local
  serviceSubnet: 10.96.0.0/12
  podSubnet: 10.244.0.0/16
scheduler: {}
controlPlaneEndpoint: $apiserver_domain:$apiserver_port
apiServer:
  ControlPlaneComponent:
    extraArgs:
      serviceNodePortRange: "30000-39999"
  timeoutForControlPlane: 4m0s
  certSANs:
    - kubernetes
    - kubernetes.default
    - kubernetes.default.svc
    - kubernetes.default.svc.cluster.local
    - localhost
    - 127.0.0.1
    - protodesign.cn
    - www.protodesign.cn
    - api.protodesign.cn
    - test.protodesign.cn
    - $apiserver_domain
    - $apiserver_ip
