version: "3"

services:
  zookeeper:
    image: "confluentinc/cp-zookeeper:latest"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    volumes:
      - "./data/zookeeper:/var/lib/zookeeper/data"
      - "./logs/zookeeper:/var/lib/zookeeper/log"
    networks:
      - kafka-net

  kafka:
    image: "confluentinc/cp-kafka:latest"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false" # 生产环境可能需要手动创建主题
      KAFKA_DELETE_TOPIC_ENABLE: "true" # 根据需要启用主题删除
    volumes:
      - "./data/kafka:/var/lib/kafka/data"
      - "./logs/kafka:/var/log/kafka"
    networks:
      - kafka-net
    ports:
      - "9092:9092"

networks:
  kafka-net:
    driver: bridge
