:: 下载特定镜像并推送到私有仓库
:: 本地docker可设置proxy
@echo off
chcp 65001 > nul

set SOURCE_REGISTRY=%1
set SOURCE_REPOSITORY=%2
set TARGET_REGISTRY=docker-registry.protodesign.cn:35000
set TARGET_REPOSITORY=%3
if "%SOURCE_REGISTRY%"=="" (
    echo Usage: %0 SOURCE_REGISTRY SOURCE_REPOSITORY [TARGET_REPOSITORY]
    exit /b 1
)
if "%SOURCE_REPOSITORY%"=="" (
    echo Usage: %0 SOURCE_REGISTRY SOURCE_REPOSITORY [TARGET_REPOSITORY]
    exit /b 1
)
if "%TARGET_REPOSITORY%"=="" (
    set TARGET_REPOSITORY=%SOURCE_REPOSITORY%
)

docker pull %SOURCE_REGISTRY%/%SOURCE_REPOSITORY%
docker tag %SOURCE_REGISTRY%/%SOURCE_REPOSITORY% %TARGET_REGISTRY%/%TARGET_REPOSITORY%
docker push %TARGET_REGISTRY%/%TARGET_REPOSITORY%
