storage:
  provider: "minio"

minio:
  endpoint: "192.168.0.18:9000"
  region: "zhuhai-1"
  accessKeyID: "Gathooh88mba5H3y2"
  secretAccessKey: "yFukp3vtIkUNck2XL3s2KOT4wyRPR71G2"
  stsAccessKeyID: "Gathooh88mba5H3y1"
  stsSecretAccessKey: "yFukp3vtIkUNck2XL3s2KOT4wyRPR71G1"
  bucketName: "document"
