version: '3'

services:
  documentservice:
    build:
      context: ..
      dockerfile: ./documentservice/Dockerfile
    image: documentservice:latest
    container_name: documentservice
    environment:
      TZ: Asia/Shanghai
    networks:
      documentservice_net_1:
        ipv4_address: 172.24.0.2
      db_net_1:
      minio_net_1:
    external_links:
      - db_1
    ports:
      - "10003:10003"
    volumes:
      - ./config/config.yaml:/app/config/config.yaml
      - ../common/jwt/config/config.yaml:/app/common/jwt/config/config.yaml
      - ../common/snowflake/config/config.yaml:/app/common/snowflake/config/config.yaml
      - ../common/storage/config/config.yaml:/app/common/storage/config/config.yaml
      - ../common/mongo/config/config.yaml:/app/common/mongo/config/config.yaml
      - ./log/all.log:/app/log/all.log

networks:
  documentservice_net_1:
    name: documentservice_net_1
    driver: bridge
    ipam:
      config:
        - subnet: 172.24.0.0/16
          gateway: 172.24.0.1
  db_net_1:
    external: true
  minio_net_1:
    external: true
