db:
  # url: root:kKEIjksvnOOIjdZ6rtzE@tcp(mysql:3306)/kcserver?charset=utf8&parseTime=True&loc=Local
  user: root
  password: kKEIjksvnOOIjdZ6rtzE
  host: localhost
  port: 3307
  database: kcserver

storage_url:
  document: http://localhost:9000
  attatch: http://localhost:9000/attatch

version_server:
  url: http://localhost:30000/generate
  min_update_interval: 10
  min_cmd_count: 1

svg2png:
  url: http://kcsvg2png:10050/svg_to_png

mongo:
  url: mongodb://root:jKKsinkjilKKLSW@localhost:27017
  db: kcserver

redis:
  addr: localhost:6379
  password: kcserver
  db: 0
  # sentinel: true
  # sentinelAddrs:
  # masterName:

safe_review:
  provider: baidu
  baidu:
    appId: 44042444
    apiKey: skYZWZolIBpo4j4olXzNRUKD
    secretKey: H5KUEgVaO08I3tDPjGp9m4LqdsKcOh40

storage:
  provider: minio
  minio:
    endpoint: "localhost:9000"
    region: "zhuhai-1"
    accessKeyID: "59L3pDWuk9oLQWIgytCI"
    secretAccessKey: "GmwAzetY1L0jU4pUAqpO7RJGIsG7k3gozVH6whoJ"
    stsAccessKeyID: "user"
    stsSecretAccessKey: "GmwAzetY1L0jU4pUAqpO7RJGIsG7k3gozVH6whoJ"
    bucketName: "document"
    attatchBucketName: "attatch"

  s3:
    endpoint: "192.168.0.18:9000"
    region: "zhuhai-1"
    accessKeyID: "Gathooh88mba5H3y2"
    secretAccessKey: "yFukp3vtIkUNck2XL3s2KOT4wyRPR71G2"
    accountID: ""
    roleName: ""
    bucketName: "document"
    attatchBucketName: "files"

  oss:
    endpoint: "oss-cn-hangzhou.aliyuncs.com"
    stsEndpoint: "sts-vpc.cn-hangzhou.aliyuncs.com"
    region: "cn-hangzhou"
    accessKeyID: "LTAI5tSm1Y5obQCwVn7X9k2x"
    secretAccessKey: "0uXxQBqG8nQC7uiyipTX6F4JkEDlcB"
    accountId: "1382280232399206"
    roleName: "ramoss"
    bucketName: "protodesign-document"
    attatchBucketName: "protodesign-files"

default_route: false
detailed_log: false
allow_cors: true

auth_server_url: https://account.test.vextra.cn
auth_client_id: kcserver
auth_client_secret: yourSecurePassword123
auth_callback_url: https://test.vextra.cn/login_callback