server:
  port: "10003"

db:
  #  dsn: "root:_IpFCT^*pui~Mac7~0%SIicRq@Z6rtzE@tcp(db_1:3306)/kcserver?charset=utf8&parseTime=True&loc=Local"
  dsn: "root:_IpFCT^*pui~Mac7~0%SIicRq@Z6rtzE@tcp(192.168.0.18:33306)/kcserver?charset=utf8&parseTime=True&loc=Local"

storagehost:
  document: "https://storage1.moss.design",
  attatch: "https://storage2.moss.design"

wx:
  appid: "xxx"
  secret: "xxx"

wxMp:
  appid: "xxx"
  secret: "xxx"

documentVersionServer:
  host: "doc-versioning-service.kc.svc.cluster.local:10040"

jwt:
  secret: "123456"
  expire_hour: 168 # 过期时间（小时）（7天）

mongo:
#  uri: "mongodb://root:kcai1212@mongo_net_1:27017"
  uri: "mongodb://root:kcai1212@192.168.0.18:27017"
  db: "kcserver"

redis:
  #  addr: "redis_net_1:6379"
  addr: "192.168.0.18:6379"
  password: "kcserver"
  db: 0

safereview:
  provider: "baidu"

  ali:
    accessKeyId: "accessKeyId"
    accessKeySecret: "accessKeySecret"
    regionId: "cn-hangzhou"
    endpoint: "green-cip.cn-hangzhou.aliyuncs.com"

  baidu:
    appId: "44042444"
    apiKey: "skYZWZolIBpo4j4olXzNRUKD"
    secretKey: "H5KUEgVaO08I3tDPjGp9m4LqdsKcOh40"

snowflake:
  workerId: 1

storage:
  provider: "minio"

  minio:
    endpoint: "192.168.0.18:9000"
    region: "zhuhai-1"
    accessKeyID: "Gathooh88mba5H3y2"
    secretAccessKey: "yFukp3vtIkUNck2XL3s2KOT4wyRPR71G2"
    stsAccessKeyID: "Gathooh88mba5H3y1"
    stsSecretAccessKey: "yFukp3vtIkUNck2XL3s2KOT4wyRPR71G1"
    bucketName: "document"
    filesBucketName: "files"

  s3:
    endpoint: "192.168.0.18:9000"
    region: "zhuhai-1"
    accessKeyID: "Gathooh88mba5H3y2"
    secretAccessKey: "yFukp3vtIkUNck2XL3s2KOT4wyRPR71G2"
    accountID: ""
    roleName: ""
    bucketName: "document"
    filesBucketName: "files"

  oss:
    endpoint: "oss-cn-hangzhou.aliyuncs.com"
    stsEndpoint: "sts-vpc.cn-hangzhou.aliyuncs.com"
    region: "cn-hangzhou"
    accessKeyID: "LTAI5tSm1Y5obQCwVn7X9k2x"
    secretAccessKey: "0uXxQBqG8nQC7uiyipTX6F4JkEDlcB"
    accountId: "1382280232399206"
    roleName: "ramoss"
    bucketName: "protodesign-document"
    filesBucketName: "protodesign-files"
 