db:
  user: root
  password: kKEIjksvnOOIjdZ6rtzE
  host: localhost
  port: 3307
  database: kcserver
  charset: utf8mb4

mongo:
  url: mongodb://root:jKKsinkjilKKLSW@localhost:27017
  db: kcserver

redis:
  addr: localhost:6379
  password: kcserver
  db: 0

storage_public_url:
  document: http://document.test.vextra.cn
  attatch: http://attatch.test.vextra.cn

safe_review:
  provider: baidu
  baidu:
    appId: 44042444
    apiKey: skYZWZolIBpo4j4olXzNRUKD
    secretKey: H5KUEgVaO08I3tDPjGp9m4LqdsKcOh40

storage:
  provider: minio
  endpoint: "192.168.0.125:9000"
  region: "zhuhai-1"
  accessKeyID: "59L3pDWuk9oLQWIgytCI"
  secretAccessKey: "GmwAzetY1L0jU4pUAqpO7RJGIsG7k3gozVH6whoJ"
  stsAccessKeyID: "user"
  stsSecretAccessKey: "GmwAzetY1L0jU4pUAqpO7RJGIsG7k3gozVH6whoJ"
  bucketName: "document"
  attatchBucketName: "attatch"

  # provider: s3
  # endpoint: "192.168.0.18:9000"
  # region: "zhuhai-1"
  # accessKeyID: "Gathooh88mba5H3y2"
  # secretAccessKey: "yFukp3vtIkUNck2XL3s2KOT4wyRPR71G2"
  # accountID: ""
  # roleName: ""
  # bucketName: "document"
  # attatchBucketName: "files"

  # provider: oss
  # endpoint: "oss-cn-hangzhou.aliyuncs.com"
  # region: "cn-hangzhou"
  # accessKeyID: "LTAI5tSm1Y5obQCwVn7X9k2x"
  # stsEndpoint: "sts-vpc.cn-hangzhou.aliyuncs.com"
  # secretAccessKey: "0uXxQBqG8nQC7uiyipTX6F4JkEDlcB"
  # accountId: "1382280232399206"
  # roleName: "ramoss"
  # bucketName: "protodesign-document"
  # attatchBucketName: "protodesign-files"

doc_update_server:
  url: http://localhost:30000/generate
  min_update_interval: 600
  min_cmd_count: 1

default_route: false
detailed_log: false
allow_cors: true

auth_server_url: https://account.test.vextra.cn
auth_client_id: kcserver
auth_client_secret: yourSecurePassword123
auth_callback_url: https://test.vextra.cn/login_callback