kind: Job
apiVersion: batch/v1
metadata:
  labels:
    app: coop-test
  name: coop-test
  namespace: kc
spec:
  parallelism: 3  # 并发数
  completions: 3  # 执行次数
  backoffLimit: 0  # 失败重试次数
  template:
    metadata:
      labels:
        app: coop-test
    spec:
      serviceAccountName: kc
      restartPolicy: Never
      containers:
        - name: app
          env:
            - name: TZ
              value: "Asia/Shanghai"
          image: "registry.protodesign.cn:36000/kcserver/coop-test:$version_tag"
          imagePullPolicy: Always
          resources: {}
