
services:
  minio:
    image: quay.io/minio/minio
    entrypoint:
    command: minio server /data --console-address ":9001"
      # - /etc/mongodb/init.sh
    container_name: minio
    networks:
      kcserver:
    restart: always
    environment:
      TZ: Asia/Shanghai
      MINIO_ROOT_USER: kcserver
      MINIO_ROOT_PASSWORD: kcai1212
      MINIO_REGION: zhuhai-1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - ./minio/data:/data
    ports:
      - "9000:9000" # 测试用
      - "9001:9001"

networks:
  kcserver:
    external: true