version: "3"

services:
  redis:
    image: "redis:alpine"
    restart: always
    volumes:
      - "./data:/data"
    networks:
      - redis_net_1
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"

networks:
  redis_net_1:
    external: true
