storage:
  provider: "minio"

minio:
  endpoint: "localhost:9000"
  accessKeyID: "Gathooh88mba5H3y"
  secretAccessKey: "yFukp3vtIkUNck2XL3s2KOT4wyRPR71G"
  stsAccessKeyID: "Gathooh88mba5H3y1"
  stsSecretAccessKey: "yFukp3vtIkUNck2XL3s2KOT4wyRPR71G1"
  bucketName: "document"
  region: ""
