version: '3'

services:
  userservice:
    build:
      context: ..
      dockerfile: ./userservice/Dockerfile
    image: userservice:latest
    container_name: userservice
    environment:
      TZ: Asia/Shanghai
    networks:
      userservice_net_1:
        ipv4_address: 172.23.0.2
      db_net_1:
    external_links:
      - db_1
    ports:
      - "10002:10002"
    volumes:
      - ./config/config.yaml:/app/config/config.yaml
      - ../common/jwt/config/config.yaml:/app/common/jwt/config/config.yaml
      - ../common/snowflake/config/config.yaml:/app/common/snowflake/config/config.yaml
      - ../common/storage/config/config.yaml:/app/common/storage/config/config.yaml
      - ./log/all.log:/app/log/all.log

networks:
  userservice_net_1:
    name: userservice_net_1
    driver: bridge
    ipam:
      config:
        - subnet: 172.23.0.0/16
          gateway: 172.23.0.1
  db_net_1:
    external: true
