safereview:
  provider: "baidu"

  ali:
    accessKeyId: "accessKeyId"
    accessKeySecret: "accessKeySecret"
    regionId: "cn-hangzhou"
    endpoint: "green-cip.cn-hangzhou.aliyuncs.com"

  baidu:
    appId: "44042444"
    apiKey: "skYZWZolIBpo4j4olXzNRUKD"
    secretKey: "H5KUEgVaO08I3tDPjGp9m4LqdsKcOh40"
