version: '3'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    networks:
      mongo_net_1:
    restart: always
    ports:
      - "27017:27017"
    environment:
      TZ: Asia/Shanghai
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: kcai1212
    volumes:
      - ./data/db:/data/db

networks:
  mongo_net_1:
    external: true