storage:
  provider: "oss"

minio:
  endpoint: "oss-cn-hangzhou-internal.aliyuncs.com"
  region: "cn-hangzhou"
  accessKeyID: "LTAI5tSm1Y5obQCwVn7X9k2x"
  secretAccessKey: "0uXxQBqG8nQC7uiyipTX6F4JkEDlcB"
  stsAccessKeyID: "LTAI5tSm1Y5obQCwVn7X9k2x"
  stsSecretAccessKey: "0uXxQBqG8nQC7uiyipTX6F4JkEDlcB"
  bucketName: "protodesign-document"
  filesBucketName: "protodesign-files"

s3:
  endpoint: "oss-cn-hangzhou-internal.aliyuncs.com"
  region: "cn-hangzhou"
  accessKeyID: "LTAI5tSm1Y5obQCwVn7X9k2x"
  secretAccessKey: "0uXxQBqG8nQC7uiyipTX6F4JkEDlcB"
  accountId: "1382280232399206"
  roleName: "ramoss"
  bucketName: "protodesign-document"
  filesBucketName: "protodesign-files"

oss:
  endpoint: "oss-cn-hangzhou-internal.aliyuncs.com"
  stsEndpoint: "sts-vpc.cn-hangzhou.aliyuncs.com"
  region: "cn-hangzhou"
  accessKeyID: "LTAI5tSm1Y5obQCwVn7X9k2x"
  secretAccessKey: "0uXxQBqG8nQC7uiyipTX6F4JkEDlcB"
  accountId: "1382280232399206"
  roleName: "ramoss"
  bucketName: "protodesign-document"
  filesBucketName: "protodesign-files"
