version: '3'

services:
  authservice:
    build:
      context: ..
      dockerfile: ./authservice/Dockerfile
    image: authservice:latest
    container_name: authservice
    environment:
      TZ: Asia/Shanghai
    networks:
      authservice_net_1:
        ipv4_address: 172.22.0.2
      db_net_1:
    external_links:
      - db_1
    ports:
      - "10001:10001"
    volumes:
      - ./config/config.yaml:/app/config/config.yaml
      - ../common/jwt/config/config.yaml:/app/common/jwt/config/config.yaml
      - ../common/snowflake/config/config.yaml:/app/common/snowflake/config/config.yaml
      - ./log/all.log:/app/log/all.log

networks:
  authservice_net_1:
    name: authservice_net_1
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/16
          gateway: 172.22.0.1
  db_net_1:
    external: true
